language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - npm
    - ocaml
    - opam
    - ocaml-native-compilers
install: sh -ex ./autoconf/travis-install.sh
cache:
  directories:
  - ${HOME}/.opam
script: sh -ex ./autoconf/travis-ci.sh && echo true
env:
  - OCAML_VERSION=system
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.1
