version: '1.0.{build}'

image:
- Ubuntu
- Visual Studio 2017
- Visual Studio 2019
- Visual Studio 2015

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    TEST: 1

configuration: Release

platform:
- x86
- x64

branches:
  only:
    - master

for:
  - matrix:
      only:
        - image: Ubuntu
    clone_folder: '/home/appveyor/projects/ocp-build'
    install:
      - sudo add-apt-repository ppa:avsm/ppa
      - sudo apt-get --assume-yes update
      - sudo apt-get --assume-yes install opam
      - opam init --yes --compiler=ocaml-base-compiler.4.07.1 --switch=ocaml-base-compiler.4.07.1
      - opam config list || true
      - ls $(opam config list | grep prefix | grep -o "/.*") || true
      - ls $(opam config list | grep prefix | grep -o "/.*")/lib || true
    build_script:
      - opam pin --yes add my-package .
      - opam install --yes my-package
      - ls $(opam config list | grep prefix | grep -o "/.*")/lib || true
      - ls $(opam config list | grep prefix | grep -o "/.*")/lib/my-package || true
      - ls $(opam config list | grep prefix | grep -o "/.*")/lib/ocp-build || true
      - opam remove --yes my-package
  - matrix:
      only:
        - image: Visual Studio 2017
    clone_folder: 'C:\projects\ocp-build'
    install:
      - set
      - C:\cygwin\setup-x86.exe -qnNdO -R C:\cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P opam,mingw64-x86_64-gcc-core
      - C:\cygwin\bin\bash.exe -lc 'opam init --yes --compiler=ocaml-base-compiler.4.07.1 --switch=ocaml-base-compiler.4.07.1'
    build_script:
      - C:\cygwin\bin\bash.exe -lc 'eval $(opam env); opam pin --yes add my-package .'
      - C:\cygwin\bin\bash.exe -lc 'eval $(opam env); opam install --yes my-package'
      - C:\cygwin\bin\bash.exe -lc 'eval $(opam env); opam remove --yes my-package'
  - matrix:
      only:
        - image: Visual Studio 2019
    clone_folder: 'C:\projects\ocp-build'
    install:
      - set
      - 'npm install -g esy@0.5.8'
    build_script:
      - esy install
      - esy build

clone_depth: 5

build: off

test: off

deploy: off
