environment:
  ACYG_ROOT: 'C:\cygwin'
  ACYG_BASH: '%CYG_ROOT%\bin\bash -lc'

version: '1.0.{build}'

image:
  - Ubuntu
  - 'Visual Studio 2017'
  - 'Visual Studio 2019'

configuration: Release

platform:
  - x86
  - x64

branches:
  only:
    - master

for:
  -
    matrix:
      only:
        -
          image: Ubuntu
    clone_folder: '/home/appveyor/projects/ocp-build'
    install:
      - apt-get update
      - apt-get install opam
      - opam init
      - opam switch create ocaml-base-compiler.4.07.1
    build_script:
      - opam pin add my-package .
      - opam install my-package
      - opam remove my-package
  -
    matrix:
      only:
        -
          image: 'Visual Studio 2017'
    environment:
      - CYG_ROOT: "C:\\cygwin"
      - CYG_BASH: "%CYG_ROOT%\\bin\\bash -lc"
    clone_folder: 'C:\projects\ocp-build'
    install:
      - "%CYG_ROOT%\\setup-x86.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P opam,mingw64-x86_64-gcc-core"
      - opam init
      - opam switch create ocaml-base-compiler.4.07.1
    build_script:
      - opam pin add my-package .
      - opam install my-package
      - opam remove my-package
  -
    matrix:
      only:
        -
          image: 'Visual Studio 2019'
    clone_folder: 'C:\projects\ocp-build'
    install:
      - 'npm i esy@0.5.8'
    build_script:
      - esy b

build: off

deploy: off
